export const LOGIN_START = "LOGIN_START"
export const LOGIN_FAIL = "LOGIN_FAIL"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"

export const LOGOUT = "LOGOUT"

export const REGISTER_START = "REGISTER_START"
export const REGISTER_FAIL = "REGISTER_FAIL"
export const REGISTER_SUCCESS = "REGISTER_SUCCESS"

export const AUTO_AUTHENTICATE = "AUTO_AUTHENTICATE"


export const CART_ADD_ITEM = "CART_ADD_ITEM"
export const CART_RESTAURANT = "CART_RESTAURANT"
export const CART_DELETE_ITEM = "CART_DELETE_ITEM"
export const CART_RESET = "CART_RESET"

